keycloak:
  realm: example
  url: http://localhost:8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/auth/realms/${keycloak.realm}
      client:
        provider:
          keycloak:
            token-uri: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/auth
            userinfo-uri: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: 75c27c34-83e1-4daf-add0-bfafe065c5f3
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud:
    discovery:
      enabled: true
  application:
    name: gateway-service
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring.main.allow-bean-definition-overriding: true
